# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xecses.awsblueprints.io
spec:
  claimNames:
    kind: ECS
    plural: ecses
  group: awsblueprints.io
  names:
    kind: XECS
    plural: xecses
  connectionSecretKeys:
    - region
    - cluster-name
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                resourceConfig:
                  description: ResourceConfig defines general properties of this AWS
                    resource.
                  properties:
                    deletionPolicy:
                      description: Defaults to Delete
                      enum:
                      - Delete
                      - Orphan
                      type: string
                    name:
                      description: Set the name of this resource in AWS to the value
                        provided by this field.
                      type: string
                    providerConfigName:
                      type: string
                    region:
                      type: string
                    tags:
                      type: object
                      additionalProperties:
                        type: string
                  required:
                  - providerConfigName
                  - region
                  type: object
                # https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#task_size
                size:
                  type: string
                  enum: [XS, S, M, L]
                  default: S
              required:
              - resourceConfig
              type: object
            status:
              properties:
                clusterArn:
                  type: string
              type: object
          type: object
