# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: ecs-service.awsblueprints.io
  labels:
    awsblueprints.io/environment: dev
    ecs.awsblueprints.io/type: service
spec:
  publishConnectionDetailsWithStoreConfigRef:
    name: default
  compositeTypeRef:
    apiVersion: awsblueprints.io/v1alpha1
    kind: XECS
  patchSets:
    - name: common-fields
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.resourceConfig.providerConfigName
          toFieldPath: spec.providerConfigRef.name
        - type: FromCompositeFieldPath
          fromFieldPath: spec.resourceConfig.deletionPolicy
          toFieldPath: spec.deletionPolicy
        - type: FromCompositeFieldPath
          fromFieldPath: spec.resourceConfig.region
          toFieldPath: spec.forProvider.region
        - type: FromCompositeFieldPath
          fromFieldPath: spec.resourceConfig.tags
          toFieldPath: spec.forProvider.tags
          policy:
            mergeOptions:
              keepMapValues: true
  resources:
    - name: task-definition
      base:
        apiVersion: ecs.aws.upbound.io/v1beta1
        kind: TaskDefinition
        metadata:
          name: sample-task
        spec:
          forProvider:
            containerDefinitions: |-
              [
                {
                  "name": "first",
                  "image": "service-first",
                  "cpu": 10,
                  "memory": 512,
                  "essential":true
                }
              ]
            family: sampleservice
      patches:
        - type: PatchSet
          patchSetName: common-fields

    - name: service
      connectionDetails:
        - name: region
          fromFieldPath: spec.forProvider.region
        - name: cluster-name
          fromFieldPath: metadata.annotations[crossplane.io/external-name]
      base:
        apiVersion: ecs.aws.upbound.io/v1beta1
        kind: Service
        metadata:
          annotations:
            upjet.upbound.io/manual-intervention: This resource requires manual intervention
              for adding task definition revision. Otherwise, resource will be updated
              to use latest revision.
          name: sample-service
        spec:
          forProvider:
            clusterSelector:
              matchLabels:
                ecs.awsblueprints.io/cluster-type: fargate
                awsblueprints.io/environment: dev
            launchType: FARGATE
            propagateTags: TASK_DEFINITION
            region: us-west-1
            taskDefinition: sampleservice
      patches:
        - type: PatchSet
          patchSetName: common-fields
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.labels[crossplane.io/claim-name]
          toFieldPath: metadata.name
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.arn
          toFieldPath: status.clusterArn
    - name: capacity-provider
      base:
        apiVersion: ecs.aws.upbound.io/v1beta1
        kind: ClusterCapacityProviders
        spec:
          forProvider:
            capacityProviders:
              - FARGATE
            clusterNameSelector:
              matchControllerRef: true
            defaultCapacityProviderStrategy:
              - base: 1
                capacityProvider: FARGATE
                weight: 100
      patches:
        - type: PatchSet
          patchSetName: common-fields


      

    

