# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: ecs-service.awsblueprints.io
  labels:
    awsblueprints.io/environment: dev
    ecs.awsblueprints.io/type: service
spec:
  publishConnectionDetailsWithStoreConfigRef:
    name: default
  compositeTypeRef:
    apiVersion: awsblueprints.io/v1alpha1
    kind: XECS
  patchSets:
    - name: common-fields
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.resourceConfig.providerConfigName
          toFieldPath: spec.providerConfigRef.name
        - type: FromCompositeFieldPath
          fromFieldPath: spec.resourceConfig.deletionPolicy
          toFieldPath: spec.deletionPolicy
        - type: FromCompositeFieldPath
          fromFieldPath: spec.resourceConfig.region
          toFieldPath: spec.forProvider.region
        - type: FromCompositeFieldPath
          fromFieldPath: spec.resourceConfig.tags
          toFieldPath: spec.forProvider.tags
          policy:
            mergeOptions:
              keepMapValues: true
  resources:
    - name: execution-role
      base:
        apiVersion: iam.aws.upbound.io/v1beta1
        kind: Role
        spec:
          forProvider:
            assumeRolePolicy: |
              {
                "Version": "2012-10-17",
                "Statement": [
                  {
                    "Effect": "Allow",
                    "Principal": {
                      "Service": "ecs-tasks.amazonaws.com"
                    },
                    "Action": "sts:AssumeRole"
                  }
                ]
              }
      patches:
        - type: PatchSet
          patchSetName: common-fields
        - type: FromCompositeFieldPath
          fromFieldPath: spec.permissionBoundaryArn
          toFieldPath: spec.forProvider.permissionsBoundary
    - name: execution-policy-attachment
      base:
        apiVersion: iam.aws.upbound.io/v1beta1
        kind: RolePolicyAttachment
        spec:
          forProvider:
            policyArn: arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
            roleSelector:
              matchControllerRef: true
      patches:
        - type: PatchSet
          patchSetName: common-fields
    - name: task-definition
      base:
        apiVersion: ecs.aws.upbound.io/v1beta1
        kind: TaskDefinition
        metadata:
          name: sample-task
        spec:
          forProvider:
            family: default
            executionRoleArnSelector:
              matchControllerRef: true
      patches:
        - type: PatchSet
          patchSetName: common-fields
        - type: FromCompositeFieldPath
          fromFieldPath: spec.size
          toFieldPath: spec.forProvider.memory
          transforms:
            - type: map
              map:
                XS: "512"
                S: "1024"
                M: "2048"
                L: "4096"
        - type: FromCompositeFieldPath
          fromFieldPath: spec.size
          toFieldPath: spec.forProvider.cpu
          transforms:
            - type: map
              map:
                XS: "256"
                S: "512"
                M: "1024"
                L: "2048"
        - fromFieldPath: metadata.labels[awsblueprints.io/application]
          toFieldPath: spec.forProvider.family
          policy:
            fromFieldPath: Required
        - type: CombineFromComposite
          toFieldPath: spec.forProvider.containerDefinitions
          policy:
              fromFieldPath: Required
          combine:
            variables:
              - fromFieldPath: metadata.labels[crossplane.io/claim-name]
              - fromFieldPath: spec.containerImage
            strategy: string
            string:
              fmt: |
                  [
                    {
                      "name": "%s",
                      "image": "%s",
                      "essential":true
                    }
                  ]

    # - name: service
    #   connectionDetails:
    #     - name: region
    #       fromFieldPath: spec.forProvider.region
    #     - name: cluster-name
    #       fromFieldPath: metadata.annotations[crossplane.io/external-name]
    #   base:
    #     apiVersion: ecs.aws.upbound.io/v1beta1
    #     kind: Service
    #     metadata:
    #       annotations:
    #         upjet.upbound.io/manual-intervention: This resource requires manual intervention
    #           for adding task definition revision. Otherwise, resource will be updated
    #           to use latest revision.
    #       name: sample-service
    #     spec:
    #       forProvider:
    #         clusterSelector:
    #           matchLabels:
    #             ecs.awsblueprints.io/cluster-type: fargate
    #             awsblueprints.io/environment: dev
    #         launchType: FARGATE
    #         propagateTags: TASK_DEFINITION
    #         region: us-west-1
    #         taskDefinition: sampleservice
    #   patches:
    #     - type: PatchSet
    #       patchSetName: common-fields
    #     - type: FromCompositeFieldPath
    #       fromFieldPath: metadata.labels[crossplane.io/claim-name]
    #       toFieldPath: metadata.name
    #     - type: ToCompositeFieldPath
    #       fromFieldPath: status.atProvider.arn
    #       toFieldPath: status.clusterArn
    # - name: capacity-provider
    #   base:
    #     apiVersion: ecs.aws.upbound.io/v1beta1
    #     kind: ClusterCapacityProviders
    #     spec:
    #       forProvider:
    #         capacityProviders:
    #           - FARGATE
    #         clusterNameSelector:
    #           matchControllerRef: true
    #         defaultCapacityProviderStrategy:
    #           - base: 1
    #             capacityProvider: FARGATE
    #             weight: 100
    #   patches:
    #     - type: PatchSet
    #       patchSetName: common-fields

