# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: example.app.awsblueprints.io
  labels:
    awsblueprints.io/environment: dev
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: app.awsblueprints.io/v1alpha1
    kind: XExampleAppLambda
  patchSets:
    - name: common-fields
      patches:
        - fromFieldPath: spec.resourceConfig
          toFieldPath: spec.resourceConfig
          policy:
            mergeOptions:
              keepMapValues: true
  resources:
    - name: dynamodb-table
      connectionDetails:
        - name: tableName
          fromConnectionSecretKey: tableName
        - name: tableArn
          fromConnectionSecretKey: tableArn
        - name: region
          fromConnectionSecretKey: region
      base:
        apiVersion: awsblueprints.io/v1alpha1
        kind: XDynamoDBTable
        spec:
          compositionSelector:
            matchLabels:
              awsblueprints.io/provider: aws
              awsblueprints.io/environment: dev
              dynamodb.awsblueprints.io/capacity: on-demand
              dynamodb.awsblueprints.io/pkType: partition
          tableIndex:
            hashKeyName: id
            hashKeyType: S
          resourceConfig:
            tags:
              - key: env
                value: dev
      patches:
        - type: PatchSet
          patchSetName: common-fields
        - type: ToCompositeFieldPath
          fromFieldPath: status.tableARN
          toFieldPath: status.tableArn
        - type: ToCompositeFieldPath
          fromFieldPath: spec.tableSpec.hashKeyName
          toFieldPath: spec.tableIndex.hashKeyName
        - type: ToCompositeFieldPath
          fromFieldPath: spec.tableSpec.hashKeyType
          toFieldPath: spec.tableIndex.hashKeyType
    - name: read-policy
      base:
        apiVersion: awsblueprints.io/v1alpha1
        kind: IAMPolicy
        spec:
          resourceConfig:
            tags:
              - key: env
                value: dev
          compositionSelector:
            matchLabels:
              awsblueprints.io/provider: aws
              awsblueprints.io/environment: dev
              iam.awsblueprints.io/policy-type: read
              iam.awsblueprints.io/service: dynamodb-table
          resourceArn: ""
      patches:
        - type: PatchSet
          patchSetName: common-fields
        - type: ToCompositeFieldPath
          fromFieldPath: status.policyArn
          toFieldPath: status.readPolicyArn
        - fromFieldPath: status.tableArn
          toFieldPath: spec.resourceArn
    - name: write-policy
      base:
        apiVersion: awsblueprints.io/v1alpha1
        kind: IAMPolicy
        spec:
          resourceConfig:
            tags:
              - key: env
                value: dev
          compositionSelector:
            matchLabels:
              awsblueprints.io/provider: aws
              awsblueprints.io/environment: dev
              iam.awsblueprints.io/policy-type: write
              iam.awsblueprints.io/service: dynamodb-table
          resourceArn: ""
      patches:
        - type: PatchSet
          patchSetName: common-fields
        - type: ToCompositeFieldPath
          fromFieldPath: status.policyArn
          toFieldPath: status.writePolicyArn
        - fromFieldPath: status.tableArn
          toFieldPath: spec.resourceArn
    - name: lambda
      base: 
        apiVersion: awsblueprints.io/v1alpha1
        kind: XLambdaFunction
        metadata:
          name: test-container-lambda
        spec:
          compositionSelector:
            matchLabels:
              awsblueprints.io/provider: aws-jet
              awsblueprints.io/environment: dev
      patches:
        - type: PatchSet
          patchSetName: common-fields
        - type: ToCompositeFieldPath
          fromFieldPath: status.functionRoleArn
          toFieldPath: status.lambdaRoleArn
        - type: FromCompositeFieldPath
          fromFieldPath: spec.permissionsBoundaryArn
          toFieldPath: spec.permissionsBoundaryArn
        - type: FromCompositeFieldPath
          fromFieldPath: spec.imageUri
          toFieldPath: spec.imageUri
