# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: awsblueprints.io/v1alpha1
kind: ECS
metadata:
  name: test-ecs-service
  namespace: default
  labels:
    awsblueprints.io/application: my-application
spec:
  compositionSelector:
    matchLabels:
      awsblueprints.io/environment: dev
      ecs.awsblueprints.io/type: service
  containerImage: "me"
  permissionBoundaryArn: arn:aws:iam::833162080385:policy/crossplaneBoundary
  size: XS
  publishConnectionDetailsTo:
    name: ecs-service
  resourceConfig:
    providerConfigName: aws-provider-config
    region: us-west-2
    tags:
      test1: value1
      test2: value2
